name: Frontend CI

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches: [ staging, main ]
    paths:
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: test -f src/index.html
